
# 1. should have lambda layers
# 2. Lambda deployment
# 3. Step Function deployment 
# 4. API Gateway deployment
# 5. API Gateway to StepFunction invocation
# 6. Secret Manager

# Tips:
#   - Do not provide static name to resources. A randomly generated resource names are much friendlier with UPDATE operations


AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  nonprodsecretarn:
    Type: String
    Description: The db password secret's arn. This will change as with the applications env i.e DEV, STAGE, PROD.
    Default: arn:aws:secretsmanager:us-east-1:942788962651:secret:supersamsecret-12365junk


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

# Create AWS Lambda layer
# Libraries in the dependencies/ folder are published into the AWS Lambda layer
  MyLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: my-lambda-layer-from-sam
      Description: My Lambda Layer created with SAM
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.7
        - python3.8
        - python3.9
        - python3.11   

# Deploy AWS lambda function and frontend it with AWS API Gateway
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - !Ref MyLambdaLayer    # <--- Reference the lambda layer, deployed above.
      Architectures:
        - x86_64
      Policies: 
        - AWSSecretsManagerGetSecretValuePolicy:   
            SecretArn: !Ref nonprodsecretarn   # <---- Attaching AWS Lambda executionrole to get access to the secret in the secret manager
      Events:     # Creates an API in the API gateway with the lambda deployment
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
# Another lambda getting deployed 
  HelloTexasFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_texas/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - !Ref MyLambdaLayer    # <--- Reference the lambda layer, deployed above.

#######################################################
#   Step Functions 
#######################################################

  SamStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      # DefinitionUri: statemachine/msg.asl.json   # <-- State machine deployed using the Amazon State Language (ASL). This will allow easy codification of existing step functions
      Definition:
        Comment: A test state machine to greet Texas
        StartAt: "Lambda Invoke"
        States:
          Lambda Invoke:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            OutputPath: "$.Payload"
            Parameters: 
              FunctionName: !GetAtt HelloTexasFunction.Arn
            Retry:
              - 
                ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            End: true
      Tracing:
        Enabled: True
      Policies:                                  # <--- IAM role for the state machine
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
                - lambda:InvokeFunction
              Resource: "*"
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL

#### Log Groups for the Step function in Amazon Cloudwatch
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup

#### Deploying API Gateway with the StepFunction as backend####

##########################################################################
#   API GATEWAY ROLE WITH PERMISSIONS TO START EXECUTING STEP FUNCTION   #
##########################################################################
  ApiGatewayStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      Path: !Join ["", ["/", !Ref "AWS::StackName", "/"]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowApiGatewayServiceToAssumeRole
            Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: CallStepFunctions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'states:StartExecution'
                Resource:
                  - !Ref SamStateMachine


##########################################################################
#   REST API GATEWAY                                                     #
##########################################################################
  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${AWS::StackName}-api


##########################################################################
#   API GATEWAY METHOD                                                   #
##########################################################################
  apiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Credentials: !GetAtt ApiGatewayStepFunctionsRole.Arn 
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:states:action/StartExecution
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates: 
          application/json: !Sub 
            - |- 
              #set($data = $util.escapeJavaScript($input.json('$'))) 
              { 
                "input": "$data", 
                "stateMachineArn": "${StateMachineArn}"
              }
            - { StateMachineArn: !Ref SamStateMachine }
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ''
      ResourceId: !GetAtt apiGateway.RootResourceId
      RestApiId: !Ref apiGateway

##########################################################################
#   API GATEWAY DEPLOYMENT                                               #
##########################################################################
  apiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - apiGatewayRootMethod
    Properties:
      RestApiId: !Ref apiGateway
      StageName: 'dev'  


Outputs: # <--- optional section
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
