
# 1. should have lambda layers
# 2. Lambda deployment
# 3. Step Function deployment
# 4. API Gateway deployment
# 5. API Gateway to StepFunction invocation
# 6. Secret Manager

# Tips:
#   - Do not provide static name to resources. A randomly generated resource names are much friendlier with UPDATE operations


AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  nonprodsecretarn:
    Type: String
    Description: The db password secret's arn. This will change as with the applications env i.e DEV, STAGE, PROD.
    Default: arn:aws:secretsmanager:us-east-1:942788962651:secret:supersamsecret-12365junk


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

# Create AWS Lambda layer
# Libraries in the dependencies/ folder are published into the AWS Lambda layer
  MyLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: my-lambda-layer-from-sam
      Description: My Lambda Layer created with SAM
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.7
        - python3.8
        - python3.9
        - python3.11   

# Deploy AWS lambda function and frontend it with AWS API Gateway
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - !Ref MyLambdaLayer    # <--- Reference the lambda layer, deployed above.
      Architectures:
        - x86_64
      Policies: 
        - AWSSecretsManagerGetSecretValuePolicy:   
            SecretArn: !Ref nonprodsecretarn   # <---- Attaching AWS Lambda executionrole to get access to the secret in the secret manager
      Events:     # Creates an API in the API gateway with the lambda deployment
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
# Another lambda getting deployed 
  HelloTexasFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_texas/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - !Ref MyLambdaLayer    # <--- Reference the lambda layer, deployed above.

#######################################################
#   Step Functions 
#######################################################

  SamStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: statemachine/msg.asl.json   # <-- State machine deployed using the Amazon State Language (ASL). This will allow easy codification of existing step functions
      Tracing:
        Enabled: True
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
                - lambda:InvokeFunction
              Resource: "*"
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL

#### Log Groups for the Step function in Amazon Cloudwatch
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup


Outputs: # <--- optional section
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
